### ISSUE TITLE
Release units 0.8-0

### ISSUE THREAD

**Issue by Enchufa2** [r-quantities/units#295]
Time for a new release! :) I've run a complete [revdep](https://github.com/r-quantities/units/tree/main/revdep) check, and we have 9 issues.

- [x] EmissV 0.665.5.2, reported in atmoschem/EmissV/issues/27
- [x] eplusr 0.15.0, reported in hongyuanjia/eplusr/issues/499
- [x] fgdr 1.1.0, reported in uribo/fgdr/issues/24
- [x] gtfs2gps 1.5-4, reported in ipeaGIT/gtfs2gps/issues/224
- [x] jpmesh 2.0.2, reported in uribo/jpmesh/issues/60
- [x] photosynthesis 2.0.1, reported in cdmuir/photosynthesis/issues/7
- [x] RWmisc 0.1.1, reported in jayrobwilliams/RWmisc/issues/8
- [x] sf 1.0-5, reported in r-spatial/sf/issues/1876
- [x] vein 0.9.4, reported in atmoschem/vein/issues/224

**Comment by Enchufa2** [comment]
All issues notified. There are basically two kinds of issues: 1) references to the old interface to install units, and 2) an incorrect usage of `all.equal`, which, due to a bug in our side, wasn't triggering errors previously, and now it is corrected.

I suggest waiting for a month or so before releasing the new version.

**Comment by edzer** [comment]
Great work - sounds good!!

**Comment by Enchufa2** [comment]
@hongyuanjia Once units 0.8.0 is uploaded with these functions removed, you package will give a WARNING due to references to missing functions. It is true that your code would never call them (because it checks units version first), but anyway the WARNING will pop up, because CRAN checks for this are not this clever. Therefore, as I said in the comment I left in your repo, you either remove those calls complete and depend on `units >= 0.7.0`, or implement [the trick I use in the constants package](https://github.com/r-quantities/constants/blob/9a61038ecd8a431f8d1d2c1be474d04e2133e574/R/constants.R#L154-L162).

**Comment by hongyuanjia** [comment]
Thanks for the trick of `getExportedValue()`. This PR (https://github.com/hongyuanjia/eplusr/pull/500) should fix it.

**Comment by Enchufa2** [comment]
@edzer A month has passed. I've repeated the revdep check and we are good to go (no new issues; some of the ones above are already solved, some of them are already on CRAN). Time for a new release?

**Comment by Enchufa2** [comment]
Oh, there's some issue with `pillar` now in the latest commit? Let me check.

**Comment by Enchufa2** [comment]
It seems that `pillar` v1.7.0 produces an output with one space less. Solved in https://github.com/r-quantities/units/commit/ccf9bfedb419ea2f3d673f4681fd11c966d4b5fd.

BTW, we have a NOTE on CRAN now saying that `udunits2` is suggested but it's orphaned. Time to remove it from Suggests?

**Comment by edzer** [comment]
Yes, time to remove `udunits2`...

**Comment by Enchufa2** [comment]
All set in 0b166d9e4fe870af838680c5e2c755839a2bba3f. We're good to go.

**Comment by edzer** [comment]
Thanks; will now submit `sf`, then `units`.

**Comment by edzer** [comment]
now on CRAN.

**Comment by Enchufa2** [comment]
Excellent, thanks!
